/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ProtocoloPagamentoRouteImport } from './routes/protocolo.pagamento'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppReembolsoRouteImport } from './routes/app.reembolso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMissoesRouteImport } from './routes/app.missoes'
import { Route as AppDermaRouteImport } from './routes/app.derma'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProtocoloPagamentoRoute = ProtocoloPagamentoRouteImport.update({
  id: '/protocolo/pagamento',
  path: '/protocolo/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppReembolsoRoute = AppReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDermaRoute = AppDermaRouteImport.update({
  id: '/derma',
  path: '/derma',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/app/derma': typeof AppDermaRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/app/derma': typeof AppDermaRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/app/derma': typeof AppDermaRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/mapa'
    | '/onboarding'
    | '/app/derma'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/reembolso'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mapa'
    | '/onboarding'
    | '/app/derma'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/reembolso'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/mapa'
    | '/onboarding'
    | '/app/derma'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/reembolso'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  MapaRoute: typeof MapaRoute
  OnboardingRoute: typeof OnboardingRoute
  ProtocoloPagamentoRoute: typeof ProtocoloPagamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/protocolo/pagamento': {
      id: '/protocolo/pagamento'
      path: '/protocolo/pagamento'
      fullPath: '/protocolo/pagamento'
      preLoaderRoute: typeof ProtocoloPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reembolso': {
      id: '/app/reembolso'
      path: '/reembolso'
      fullPath: '/app/reembolso'
      preLoaderRoute: typeof AppReembolsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missoes': {
      id: '/app/missoes'
      path: '/missoes'
      fullPath: '/app/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/derma': {
      id: '/app/derma'
      path: '/derma'
      fullPath: '/app/derma'
      preLoaderRoute: typeof AppDermaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDermaRoute: typeof AppDermaRoute
  AppMissoesRoute: typeof AppMissoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReembolsoRoute: typeof AppReembolsoRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDermaRoute: AppDermaRoute,
  AppMissoesRoute: AppMissoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReembolsoRoute: AppReembolsoRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  MapaRoute: MapaRoute,
  OnboardingRoute: OnboardingRoute,
  ProtocoloPagamentoRoute: ProtocoloPagamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
