/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as QuizzRouteImport } from './routes/quizz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProtocoloPagamentoRouteImport } from './routes/protocolo.pagamento'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppRotinaRouteImport } from './routes/app.rotina'
import { Route as AppRegistrarRouteImport } from './routes/app.registrar'
import { Route as AppReembolsoRouteImport } from './routes/app.reembolso'
import { Route as AppProtocoloRouteImport } from './routes/app.protocolo'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMissoesRouteImport } from './routes/app.missoes'
import { Route as AppFotoRouteImport } from './routes/app.foto'
import { Route as AppExamesRouteImport } from './routes/app.exames'
import { Route as AppDermaRouteImport } from './routes/app.derma'
import { Route as AppAvaliacaoRouteImport } from './routes/app.avaliacao'
import { Route as AppAnamneseRouteImport } from './routes/app.anamnese'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminProtocoloRouteImport } from './routes/admin.protocolo'
import { Route as AdminMetricasRouteImport } from './routes/admin.metricas'
import { Route as AdminMapaRouteImport } from './routes/admin.mapa'
import { Route as AdminFunisRouteImport } from './routes/admin.funis'
import { Route as AdminExamesRouteImport } from './routes/admin.exames'
import { Route as AdminDermaRouteImport } from './routes/admin.derma'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AppGuiasIndexRouteImport } from './routes/app.guias.index'
import { Route as AppGuiasSlugRouteImport } from './routes/app.guias.$slug'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiPublicHooksLiberarPremiumRouteImport } from './routes/api/public/hooks/liberar-premium'
import { Route as ApiPublicHooksEnviarMsgRouteImport } from './routes/api/public/hooks/enviar-msg'
import { Route as ApiPublicHooksCronTickRouteImport } from './routes/api/public/hooks/cron-tick'

const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzRoute = QuizzRouteImport.update({
  id: '/quizz',
  path: '/quizz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProtocoloPagamentoRoute = ProtocoloPagamentoRouteImport.update({
  id: '/protocolo/pagamento',
  path: '/protocolo/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppRotinaRoute = AppRotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrarRoute = AppRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AppRoute,
} as any)
const AppReembolsoRoute = AppReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocoloRoute = AppProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFotoRoute = AppFotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => AppRoute,
} as any)
const AppExamesRoute = AppExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AppRoute,
} as any)
const AppDermaRoute = AppDermaRouteImport.update({
  id: '/derma',
  path: '/derma',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacaoRoute = AppAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => AppRoute,
} as any)
const AppAnamneseRoute = AppAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtocoloRoute = AdminProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaRoute = AdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFunisRoute = AdminFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamesRoute = AdminExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDermaRoute = AdminDermaRouteImport.update({
  id: '/derma',
  path: '/derma',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AppGuiasIndexRoute = AppGuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiasSlugRoute = AppGuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLiberarPremiumRoute =
  ApiPublicHooksLiberarPremiumRouteImport.update({
    id: '/api/public/hooks/liberar-premium',
    path: '/api/public/hooks/liberar-premium',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnviarMsgRoute = ApiPublicHooksEnviarMsgRouteImport.update({
  id: '/api/public/hooks/enviar-msg',
  path: '/api/public/hooks/enviar-msg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCronTickRoute = ApiPublicHooksCronTickRouteImport.update({
  id: '/api/public/hooks/cron-tick',
  path: '/api/public/hooks/cron-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/mapa': typeof MapaRoute
  '/oferta': typeof OfertaRoute
  '/onboarding': typeof OnboardingRoute
  '/quizz': typeof QuizzRoute
  '/upsell': typeof UpsellRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/derma': typeof AdminDermaRoute
  '/admin/exames': typeof AdminExamesRoute
  '/admin/funis': typeof AdminFunisRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/protocolo': typeof AdminProtocoloRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/anamnese': typeof AppAnamneseRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/derma': typeof AppDermaRoute
  '/app/exames': typeof AppExamesRoute
  '/app/foto': typeof AppFotoRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/protocolo': typeof AppProtocoloRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/rotina': typeof AppRotinaRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/guias/$slug': typeof AppGuiasSlugRoute
  '/app/guias/': typeof AppGuiasIndexRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/enviar-msg': typeof ApiPublicHooksEnviarMsgRoute
  '/api/public/hooks/liberar-premium': typeof ApiPublicHooksLiberarPremiumRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/mapa': typeof MapaRoute
  '/oferta': typeof OfertaRoute
  '/onboarding': typeof OnboardingRoute
  '/quizz': typeof QuizzRoute
  '/upsell': typeof UpsellRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/derma': typeof AdminDermaRoute
  '/admin/exames': typeof AdminExamesRoute
  '/admin/funis': typeof AdminFunisRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/protocolo': typeof AdminProtocoloRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/anamnese': typeof AppAnamneseRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/derma': typeof AppDermaRoute
  '/app/exames': typeof AppExamesRoute
  '/app/foto': typeof AppFotoRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/protocolo': typeof AppProtocoloRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/rotina': typeof AppRotinaRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/guias/$slug': typeof AppGuiasSlugRoute
  '/app/guias': typeof AppGuiasIndexRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/enviar-msg': typeof ApiPublicHooksEnviarMsgRoute
  '/api/public/hooks/liberar-premium': typeof ApiPublicHooksLiberarPremiumRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/mapa': typeof MapaRoute
  '/oferta': typeof OfertaRoute
  '/onboarding': typeof OnboardingRoute
  '/quizz': typeof QuizzRoute
  '/upsell': typeof UpsellRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/derma': typeof AdminDermaRoute
  '/admin/exames': typeof AdminExamesRoute
  '/admin/funis': typeof AdminFunisRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/protocolo': typeof AdminProtocoloRoute
  '/admin_/login': typeof AdminLoginRoute
  '/app/anamnese': typeof AppAnamneseRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/derma': typeof AppDermaRoute
  '/app/exames': typeof AppExamesRoute
  '/app/foto': typeof AppFotoRoute
  '/app/missoes': typeof AppMissoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/protocolo': typeof AppProtocoloRoute
  '/app/reembolso': typeof AppReembolsoRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/rotina': typeof AppRotinaRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/protocolo/pagamento': typeof ProtocoloPagamentoRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/guias/$slug': typeof AppGuiasSlugRoute
  '/app/guias/': typeof AppGuiasIndexRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/enviar-msg': typeof ApiPublicHooksEnviarMsgRoute
  '/api/public/hooks/liberar-premium': typeof ApiPublicHooksLiberarPremiumRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/definir-senha'
    | '/entrar'
    | '/mapa'
    | '/oferta'
    | '/onboarding'
    | '/quizz'
    | '/upsell'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/derma'
    | '/admin/exames'
    | '/admin/funis'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/protocolo'
    | '/admin/login'
    | '/app/anamnese'
    | '/app/avaliacao'
    | '/app/derma'
    | '/app/exames'
    | '/app/foto'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/protocolo'
    | '/app/reembolso'
    | '/app/registrar'
    | '/app/rotina'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/admin/'
    | '/app/'
    | '/api/public/track'
    | '/app/guias/$slug'
    | '/app/guias/'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/enviar-msg'
    | '/api/public/hooks/liberar-premium'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/entrar'
    | '/mapa'
    | '/oferta'
    | '/onboarding'
    | '/quizz'
    | '/upsell'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/derma'
    | '/admin/exames'
    | '/admin/funis'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/protocolo'
    | '/admin/login'
    | '/app/anamnese'
    | '/app/avaliacao'
    | '/app/derma'
    | '/app/exames'
    | '/app/foto'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/protocolo'
    | '/app/reembolso'
    | '/app/registrar'
    | '/app/rotina'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/admin'
    | '/app'
    | '/api/public/track'
    | '/app/guias/$slug'
    | '/app/guias'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/enviar-msg'
    | '/api/public/hooks/liberar-premium'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/kiwify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/definir-senha'
    | '/entrar'
    | '/mapa'
    | '/oferta'
    | '/onboarding'
    | '/quizz'
    | '/upsell'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/derma'
    | '/admin/exames'
    | '/admin/funis'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/protocolo'
    | '/admin_/login'
    | '/app/anamnese'
    | '/app/avaliacao'
    | '/app/derma'
    | '/app/exames'
    | '/app/foto'
    | '/app/missoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/protocolo'
    | '/app/reembolso'
    | '/app/registrar'
    | '/app/rotina'
    | '/app/whatsapp'
    | '/protocolo/pagamento'
    | '/admin/'
    | '/app/'
    | '/api/public/track'
    | '/app/guias/$slug'
    | '/app/guias/'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/enviar-msg'
    | '/api/public/hooks/liberar-premium'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  EntrarRoute: typeof EntrarRoute
  MapaRoute: typeof MapaRoute
  OfertaRoute: typeof OfertaRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizzRoute: typeof QuizzRoute
  UpsellRoute: typeof UpsellRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProtocoloPagamentoRoute: typeof ProtocoloPagamentoRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicHooksCronTickRoute: typeof ApiPublicHooksCronTickRoute
  ApiPublicHooksEnviarMsgRoute: typeof ApiPublicHooksEnviarMsgRoute
  ApiPublicHooksLiberarPremiumRoute: typeof ApiPublicHooksLiberarPremiumRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizz': {
      id: '/quizz'
      path: '/quizz'
      fullPath: '/quizz'
      preLoaderRoute: typeof QuizzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/protocolo/pagamento': {
      id: '/protocolo/pagamento'
      path: '/protocolo/pagamento'
      fullPath: '/protocolo/pagamento'
      preLoaderRoute: typeof ProtocoloPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rotina': {
      id: '/app/rotina'
      path: '/rotina'
      fullPath: '/app/rotina'
      preLoaderRoute: typeof AppRotinaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registrar': {
      id: '/app/registrar'
      path: '/registrar'
      fullPath: '/app/registrar'
      preLoaderRoute: typeof AppRegistrarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reembolso': {
      id: '/app/reembolso'
      path: '/reembolso'
      fullPath: '/app/reembolso'
      preLoaderRoute: typeof AppReembolsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protocolo': {
      id: '/app/protocolo'
      path: '/protocolo'
      fullPath: '/app/protocolo'
      preLoaderRoute: typeof AppProtocoloRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missoes': {
      id: '/app/missoes'
      path: '/missoes'
      fullPath: '/app/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/foto': {
      id: '/app/foto'
      path: '/foto'
      fullPath: '/app/foto'
      preLoaderRoute: typeof AppFotoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exames': {
      id: '/app/exames'
      path: '/exames'
      fullPath: '/app/exames'
      preLoaderRoute: typeof AppExamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/derma': {
      id: '/app/derma'
      path: '/derma'
      fullPath: '/app/derma'
      preLoaderRoute: typeof AppDermaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avaliacao': {
      id: '/app/avaliacao'
      path: '/avaliacao'
      fullPath: '/app/avaliacao'
      preLoaderRoute: typeof AppAvaliacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anamnese': {
      id: '/app/anamnese'
      path: '/anamnese'
      fullPath: '/app/anamnese'
      preLoaderRoute: typeof AppAnamneseRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/protocolo': {
      id: '/admin/protocolo'
      path: '/protocolo'
      fullPath: '/admin/protocolo'
      preLoaderRoute: typeof AdminProtocoloRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa': {
      id: '/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AdminMapaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funis': {
      id: '/admin/funis'
      path: '/funis'
      fullPath: '/admin/funis'
      preLoaderRoute: typeof AdminFunisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exames': {
      id: '/admin/exames'
      path: '/exames'
      fullPath: '/admin/exames'
      preLoaderRoute: typeof AdminExamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/derma': {
      id: '/admin/derma'
      path: '/derma'
      fullPath: '/admin/derma'
      preLoaderRoute: typeof AdminDermaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/guias/': {
      id: '/app/guias/'
      path: '/guias'
      fullPath: '/app/guias/'
      preLoaderRoute: typeof AppGuiasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guias/$slug': {
      id: '/app/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/app/guias/$slug'
      preLoaderRoute: typeof AppGuiasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/liberar-premium': {
      id: '/api/public/hooks/liberar-premium'
      path: '/api/public/hooks/liberar-premium'
      fullPath: '/api/public/hooks/liberar-premium'
      preLoaderRoute: typeof ApiPublicHooksLiberarPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enviar-msg': {
      id: '/api/public/hooks/enviar-msg'
      path: '/api/public/hooks/enviar-msg'
      fullPath: '/api/public/hooks/enviar-msg'
      preLoaderRoute: typeof ApiPublicHooksEnviarMsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron-tick': {
      id: '/api/public/hooks/cron-tick'
      path: '/api/public/hooks/cron-tick'
      fullPath: '/api/public/hooks/cron-tick'
      preLoaderRoute: typeof ApiPublicHooksCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminDermaRoute: typeof AdminDermaRoute
  AdminExamesRoute: typeof AdminExamesRoute
  AdminFunisRoute: typeof AdminFunisRoute
  AdminMapaRoute: typeof AdminMapaRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminProtocoloRoute: typeof AdminProtocoloRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminDermaRoute: AdminDermaRoute,
  AdminExamesRoute: AdminExamesRoute,
  AdminFunisRoute: AdminFunisRoute,
  AdminMapaRoute: AdminMapaRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminProtocoloRoute: AdminProtocoloRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnamneseRoute: typeof AppAnamneseRoute
  AppAvaliacaoRoute: typeof AppAvaliacaoRoute
  AppDermaRoute: typeof AppDermaRoute
  AppExamesRoute: typeof AppExamesRoute
  AppFotoRoute: typeof AppFotoRoute
  AppMissoesRoute: typeof AppMissoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppProtocoloRoute: typeof AppProtocoloRoute
  AppReembolsoRoute: typeof AppReembolsoRoute
  AppRegistrarRoute: typeof AppRegistrarRoute
  AppRotinaRoute: typeof AppRotinaRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGuiasSlugRoute: typeof AppGuiasSlugRoute
  AppGuiasIndexRoute: typeof AppGuiasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnamneseRoute: AppAnamneseRoute,
  AppAvaliacaoRoute: AppAvaliacaoRoute,
  AppDermaRoute: AppDermaRoute,
  AppExamesRoute: AppExamesRoute,
  AppFotoRoute: AppFotoRoute,
  AppMissoesRoute: AppMissoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppProtocoloRoute: AppProtocoloRoute,
  AppReembolsoRoute: AppReembolsoRoute,
  AppRegistrarRoute: AppRegistrarRoute,
  AppRotinaRoute: AppRotinaRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
  AppGuiasSlugRoute: AppGuiasSlugRoute,
  AppGuiasIndexRoute: AppGuiasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  EntrarRoute: EntrarRoute,
  MapaRoute: MapaRoute,
  OfertaRoute: OfertaRoute,
  OnboardingRoute: OnboardingRoute,
  QuizzRoute: QuizzRoute,
  UpsellRoute: UpsellRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProtocoloPagamentoRoute: ProtocoloPagamentoRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicHooksCronTickRoute: ApiPublicHooksCronTickRoute,
  ApiPublicHooksEnviarMsgRoute: ApiPublicHooksEnviarMsgRoute,
  ApiPublicHooksLiberarPremiumRoute: ApiPublicHooksLiberarPremiumRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
